#!/usr/bin/env python3
import numpy as np
from crop_classification.utils import read_data, print_metrics


def main():
    X_tr, X_te, X_balanced, y_tr, y_te, y_balanced = read_data()

    majority_cls = np.argmax(np.bincount(y_te))

    print("\nTest on imbalanced dataset:")
    y_pred = np.zeros(y_te.shape) + majority_cls
    print_metrics(y_pred, y_te)

    print("\nTest on balanced dataset:")
    y_pred = np.zeros(y_balanced.shape) + majority_cls
    print_metrics(y_pred, y_balanced)


if __name__ == "__main__":
    main()
