#!/usr/bin/env python3
import argparse
import pandas as pd
import numpy as np
import torch
import torch.optim as optim
from torch import nn
from crop_classification.utils import read_data, accuracy
from sklearn import tree


def main(args):
    X_tr, X_te, Y_tr, Y_te = read_data()

    clf = tree.DecisionTreeClassifier()
    clf = clf.fit(X_tr, Y_tr)

    Y_te_hat = clf.predict(X_te)
    acc = accuracy(Y_te_hat, Y_te)
    print(acc)

    tree.plot_tree(clf)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input",
        type=str,
        help="Input file name",
    )

    args = parser.parse_args()

    main(args)
