#!/usr/bin/env python3
from crop_classification.utils import read_data, print_metrics
from sklearn.ensemble import RandomForestClassifier


def main():
    X_tr, X_te, X_balanced, y_tr, y_te, y_balanced = read_data()

    clf = RandomForestClassifier()
    clf = clf.fit(X_tr, y_tr)

    print("\nTest on imbalanced dataset:")
    y_pred = clf.predict(X_te)
    print_metrics(y_pred, y_te)

    print("\nTest on balanced dataset:")
    y_pred = clf.predict(X_balanced)
    print_metrics(y_pred, y_balanced)


if __name__ == "__main__":
    main()
